#
#     DEVELOPMENT BRANCH
#
# build in Debug mode and deploy as pre-release

branches:
  only:
    - develop

configuration: Debug
platform: Any CPU

environment:
  use_build_number_in_packages: true

artifacts:
  - path: src\build\Debug
  - path: src\build\nuget\*.nupkg

cache:
  - src\packages -> src\**\packages.config

before_build:
  - nuget restore "src\Radical.CQRS.sln"


build:
  project: src\Radical.CQRS.sln
  verbosity: minimal

after_build:
  - md "src\build\nuget"
  - nuget pack "src\Radical.CQRS.nuspec" -Version "%GitVersion_NuGetVersion%" -Properties "configuration=%CONFIGURATION%" -OutputDirectory "src\build\nuget"

pull_requests:
  do_not_increment_build_number: true

deploy:
  - provider: Environment
    name: NuGet public feed
  
  - provider: GitHub    
    release: '%GitVersion_NuGetVersion%'
    description: 'Release %GitVersion_NuGetVersion%'
    prerelease: true
    auth_token:
      secure: 2ijF4OfPYfIUTunubL/Z04ogADL9sx/gKW1jMRNJnAa1OpHZpSvCKmP0gvNs8C7h
    artifact: /.*\.nupkg/, src\build\Debug.zip
    on:
      branch: develop
      appveyor_repo_tag: true
