#
#     DEVELOPMENT BRANCH
#
# build in Debug mode and deploy to MyGet.org as pre-release
branches:
  only:
    - develop

configuration: Debug
platform: Any CPU

environment:
  use_build_number_in_packages: true

cache:
  - src\packages -> src\**\packages.config

before_build:
  - nuget restore "src\Radical.sln"


build:
  project: src\Radical.sln
  verbosity: minimal

# after_build:
#   - md "src\build\nuget"
#   - nuget pack "src\nuget\Radical.nuspec" -Version "%package_version%" -Properties "configuration=%CONFIGURATION%" -OutputDirectory "src\build\nuget"

pull_requests:
    do_not_increment_build_number: true

deploy:
  - provider: Environment
    name: NuGet feed
    on:
      branch: develop